"""Compute business insights straight from the executed result.

Every insight string here is derived from an actual number in `result.table`
(or from the full dataframe for context, e.g. total revenue for a percentage-
of-whole calculation). Nothing here is generated by an LLM, so insights can
never be fabricated - they satisfy the "based on returned data, not
hallucinated" requirement by construction.

If an LLM is available, conversation_agent.py may ask it to *rephrase* these
facts more naturally, but it is always given the exact numbers below and told
not to alter them.
"""

from __future__ import annotations

from typing import List

import pandas as pd

from .safe_executor import ExecutionResult

MAX_INSIGHTS = 5


def _pct(part: float, whole: float) -> float:
    if not whole:
        return 0.0
    return round((part / whole) * 100, 1)


def generate_insights(result: ExecutionResult, full_df: pd.DataFrame) -> List[str]:
    table = result.table
    insights: List[str] = []
    if table is None or table.empty:
        return ["No matching data was found for this question."]

    op = result.operation
    metric = result.metric or "revenue"

    if op == "top_n":
        total = full_df[metric].sum()
        top_row = table.iloc[0]
        insights.append(
            f"{top_row[result.dimension]} leads with {metric} of {top_row[metric]:,.0f}, "
            f"{_pct(top_row[metric], total)}% of total {metric}."
        )
        if len(table) > 1:
            insights.append(
                f"The top {len(table)} {result.dimension.replace('_', ' ')} entries together "
                f"account for {_pct(table[metric].sum(), total)}% of total {metric}."
            )
        if len(table) > 2:
            spread = table.iloc[0][metric] - table.iloc[-1][metric]
            insights.append(
                f"The gap between the highest and lowest shown is {spread:,.0f} in {metric}."
            )

    elif op == "filter_show":
        total_metric = table[metric].sum()
        insights.append(f"Combined {metric} across the filtered selection is {total_metric:,.0f}.")
        if len(table) > 1:
            top_row = table.iloc[0]
            insights.append(
                f"{top_row[result.dimension]} is the largest contributor within this view, "
                f"at {_pct(top_row[metric], total_metric)}% of the filtered total."
            )

    elif op == "trend":
        first, last = table.iloc[0], table.iloc[-1]
        change = last[metric] - first[metric]
        direction = "increased" if change > 0 else ("decreased" if change < 0 else "stayed flat")
        insights.append(
            f"{metric.title()} {direction} from {first[metric]:,.0f} to {last[metric]:,.0f} "
            f"across the shown periods."
        )
        peak = table.loc[table[metric].idxmax()]
        insights.append(f"The highest point in the series was {peak[metric]:,.0f}.")

    elif op == "compare":
        if len(table) >= 2:
            a, b = table.iloc[0], table.iloc[1]
            diff = a[metric] - b[metric]
            insights.append(
                f"{a[result.dimension]} recorded {a[metric]:,.0f} in {metric} versus "
                f"{b[metric]:,.0f} for {b[result.dimension]} ({abs(diff):,.0f} difference)."
            )
            if "profit" in table.columns and metric != "profit":
                insights.append(
                    f"Profit was {a['profit']:,.0f} for {a[result.dimension]} and "
                    f"{b['profit']:,.0f} for {b[result.dimension]}."
                )

    elif op in ("growth", "declining"):
        if "pct_change" in table.columns:
            for _, row in table.head(3).iterrows():
                trend_word = "grew" if row["pct_change"] > 0 else "declined"
                insights.append(
                    f"{row[result.dimension]} {trend_word} {abs(row['pct_change']):.1f}% "
                    f"period-over-period ({row['previous']:,.0f} -> {row['latest']:,.0f})."
                )
        if not insights:
            insights.append("No period-over-period change was detected in the current filter.")

    elif op == "average_metric":
        row = table.iloc[0]
        avg_col = [c for c in table.columns if c.startswith("average_")][0]
        insights.append(f"The average {metric} is {row[avg_col]:,.2f}, based on {int(row['rows']):,} rows.")

    elif op == "summary":
        as_dict = dict(zip(table["metric"], table["value"]))
        insights.append(f"Total revenue is {as_dict.get('total_revenue', 0):,.0f}.")
        insights.append(f"Total profit is {as_dict.get('total_profit', 0):,.0f}.")
        insights.append(f"Top category is {as_dict.get('top_category', 'N/A')}, top region is {as_dict.get('top_region', 'N/A')}.")

    elif op == "correlation":
        insights.append("The matrix shows how strongly each pair of numeric metrics moves together (1 = perfectly together, -1 = perfectly opposite).")

    return insights[:MAX_INSIGHTS] if insights else ["No specific insights could be derived from this result."]
